"""
Task 3: extract simple pricing-adjustment rules and test robustness.

This script compresses the task-2 equal-weight optimal alpha path into shallow
decision-tree rules. The learned rules are then used as an operational policy:

    u_i,t = alpha_rule_i,t * f_i,t

where f_i,t is the first-question theoretical adjustment. Robustness is checked
under several international-oil-volatility scenarios generated by scaling and
shifting the theoretical adjustment path.

Outputs:
    result/task3_rule_tree_gasoline.txt
    result/task3_rule_tree_diesel.txt
    result/task3_rule_fit_metrics.csv
    result/task3_simple_rule_alpha_path.csv
    result/task3_simple_rule_strategy_comparison.csv
    result/task3_simple_rule_dimension_mean_summary.csv
    result/task3_robustness_scenario_summary.csv
    result/task3_robustness_dimension_means.csv
    result/task3_simple_rule_dimension_means.png
    result/task3_robustness_total_loss.png
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor, export_text

from compare_task2_policy_strategies import evaluate_adjustment_path
from task2_social_welfare_loss import EPS, get_weight_scenario, load_parameters


ROOT = Path(__file__).resolve().parent.parent
RESULT_DIR = ROOT / "result"

FEATURE_COLUMNS = [
    "f_self",
    "f_other",
    "abs_f_self",
    "same_direction_up",
    "same_direction_down",
    "cpi_yoy",
    "brent_pressure_h",
    "S_lag",
    "prev_u",
]

SCENARIOS = [
    {
        "scenario": "baseline",
        "scenario_cn": "基准波动",
        "scenario_en": "Baseline",
        "positive_scale": 1.00,
        "negative_scale": 1.00,
    },
    {
        "scenario": "low_volatility_075",
        "scenario_cn": "低波动",
        "scenario_en": "Low vol 0.75x",
        "positive_scale": 0.75,
        "negative_scale": 0.75,
    },
    {
        "scenario": "high_volatility_125",
        "scenario_cn": "高波动1.25倍",
        "scenario_en": "High vol 1.25x",
        "positive_scale": 1.25,
        "negative_scale": 1.25,
    },
    {
        "scenario": "high_volatility_150",
        "scenario_cn": "高波动1.50倍",
        "scenario_en": "High vol 1.50x",
        "positive_scale": 1.50,
        "negative_scale": 1.50,
    },
    {
        "scenario": "extreme_volatility_200",
        "scenario_cn": "极端波动2.00倍",
        "scenario_en": "Extreme vol 2.00x",
        "positive_scale": 2.00,
        "negative_scale": 2.00,
    },
    {
        "scenario": "upward_skew_volatility",
        "scenario_cn": "上行波动偏强",
        "scenario_en": "Upward-skewed vol",
        "positive_scale": 1.50,
        "negative_scale": 0.75,
    },
]


def add_state_features(
    events: pd.DataFrame,
    u_gasoline: np.ndarray,
    u_diesel: np.ndarray,
    params: dict[str, float],
) -> pd.DataFrame:
    data = events.copy().sort_values("date").reset_index(drop=True)
    rho = float(params["rho"])
    s_g = 0.0
    s_d = 0.0
    prev_u_g = 0.0
    prev_u_d = 0.0
    rows = []
    for idx, row in data.iterrows():
        rows.append(
            {
                "date": row["date"],
                "S_gasoline_lag": s_g,
                "S_diesel_lag": s_d,
                "prev_u_gasoline": prev_u_g,
                "prev_u_diesel": prev_u_d,
            }
        )
        f_g = float(row["f_gasoline"])
        f_d = float(row["f_diesel"])
        u_g = float(u_gasoline[idx])
        u_d = float(u_diesel[idx])
        s_g = rho * s_g + f_g - u_g
        s_d = rho * s_d + f_d - u_d
        prev_u_g = u_g
        prev_u_d = u_d
    state = pd.DataFrame(rows)
    return data.merge(state, on="date", how="left")


def make_feature_frame(data: pd.DataFrame, fuel: str) -> pd.DataFrame:
    if fuel == "gasoline":
        f_self = data["f_gasoline"]
        f_other = data["f_diesel"]
        s_lag = data["S_gasoline_lag"]
        prev_u = data["prev_u_gasoline"]
    elif fuel == "diesel":
        f_self = data["f_diesel"]
        f_other = data["f_gasoline"]
        s_lag = data["S_diesel_lag"]
        prev_u = data["prev_u_diesel"]
    else:
        raise ValueError(f"Unknown fuel: {fuel}")

    same_direction_up = ((data["f_gasoline"] > 0) & (data["f_diesel"] > 0)).astype(int)
    same_direction_down = ((data["f_gasoline"] < 0) & (data["f_diesel"] < 0)).astype(int)
    return pd.DataFrame(
        {
            "f_self": f_self,
            "f_other": f_other,
            "abs_f_self": f_self.abs(),
            "same_direction_up": same_direction_up,
            "same_direction_down": same_direction_down,
            "cpi_yoy": data["cpi_yoy"],
            "brent_pressure_h": data["brent_pressure_h"],
            "S_lag": s_lag,
            "prev_u": prev_u,
        }
    )


def fit_rule_tree(training: pd.DataFrame, fuel: str) -> tuple[DecisionTreeRegressor, dict[str, float], str]:
    target_col = f"alpha_{fuel}"
    f_col = f"f_{fuel}"
    sample = training.loc[training[f_col].abs() > EPS].copy()
    x = make_feature_frame(sample, fuel)
    y = sample[target_col].to_numpy()

    tree = DecisionTreeRegressor(
        max_depth=3,
        min_samples_leaf=12,
        random_state=0,
    )
    tree.fit(x[FEATURE_COLUMNS], y)

    pred = np.clip(tree.predict(x[FEATURE_COLUMNS]), 0.0, 1.0)
    pred_rounded = round_alpha(pred)
    metrics = {
        "fuel": fuel,
        "n": len(sample),
        "mae_raw_tree": mean_absolute_error(y, pred),
        "rmse_raw_tree": mean_squared_error(y, pred) ** 0.5,
        "r2_raw_tree": r2_score(y, pred),
        "mae_rounded_rule": mean_absolute_error(y, pred_rounded),
        "rmse_rounded_rule": mean_squared_error(y, pred_rounded) ** 0.5,
        "r2_rounded_rule": r2_score(y, pred_rounded),
    }
    rule_text = export_text(tree, feature_names=FEATURE_COLUMNS, decimals=2)
    return tree, metrics, rule_text


def round_alpha(values: np.ndarray | float) -> np.ndarray | float:
    rounded = np.round(np.asarray(values, dtype=float) / 0.05) * 0.05
    rounded = np.clip(rounded, 0.0, 1.0)
    if np.isscalar(values):
        return float(rounded)
    return rounded


def predict_rule_path(
    events: pd.DataFrame,
    params: dict[str, float],
    gasoline_tree: DecisionTreeRegressor,
    diesel_tree: DecisionTreeRegressor,
) -> pd.DataFrame:
    data = events.copy().sort_values("date").reset_index(drop=True)
    rho = float(params["rho"])
    s_g = 0.0
    s_d = 0.0
    prev_u_g = 0.0
    prev_u_d = 0.0
    rows = []
    for row in data.itertuples(index=False):
        state = pd.DataFrame(
            [
                {
                    "f_gasoline": float(row.f_gasoline),
                    "f_diesel": float(row.f_diesel),
                    "cpi_yoy": float(row.cpi_yoy),
                    "brent_pressure_h": float(row.brent_pressure_h),
                    "S_gasoline_lag": s_g,
                    "S_diesel_lag": s_d,
                    "prev_u_gasoline": prev_u_g,
                    "prev_u_diesel": prev_u_d,
                }
            ]
        )
        if abs(float(row.f_gasoline)) <= EPS:
            alpha_g = 0.0
        else:
            xg = make_feature_frame(state, "gasoline")
            alpha_g = round_alpha(gasoline_tree.predict(xg[FEATURE_COLUMNS])[0])
        if abs(float(row.f_diesel)) <= EPS:
            alpha_d = 0.0
        else:
            xd = make_feature_frame(state, "diesel")
            alpha_d = round_alpha(diesel_tree.predict(xd[FEATURE_COLUMNS])[0])

        f_g = float(row.f_gasoline)
        f_d = float(row.f_diesel)
        u_g = float(alpha_g) * f_g
        u_d = float(alpha_d) * f_d
        rows.append(
            {
                "date": row.date,
                "f_gasoline": f_g,
                "f_diesel": f_d,
                "alpha_rule_gasoline": alpha_g,
                "alpha_rule_diesel": alpha_d,
                "rule_u_gasoline": u_g,
                "rule_u_diesel": u_d,
                "S_gasoline_lag": s_g,
                "S_diesel_lag": s_d,
                "prev_u_gasoline": prev_u_g,
                "prev_u_diesel": prev_u_d,
            }
        )
        s_g = rho * s_g + f_g - u_g
        s_d = rho * s_d + f_d - u_d
        prev_u_g = u_g
        prev_u_d = u_d
    return pd.DataFrame(rows)


def summarize_strategy(
    name: str,
    eval_result: dict[str, pd.DataFrame | float],
) -> dict[str, float | str]:
    event = eval_result["event_loss"]
    monthly = eval_result["monthly_loss"]
    return {
        "strategy": name,
        "total_loss": float(event["weighted_event_loss"].sum()),
        "mean_event_loss": float(event["weighted_event_loss"].mean()),
        "LC_mean": float(event["LC"].mean()),
        "LF_mean": float(event["LF"].mean()),
        "LV_mean": float(event["LV"].mean()),
        "Lpi_mean": float(monthly["Lpi"].mean()),
        "LE_LT_mean": float((event["LE"] + event["LT"]).mean()),
        "mean_abs_u_gasoline": float(event["u_gasoline"].abs().mean()),
        "mean_abs_u_diesel": float(event["u_diesel"].abs().mean()),
    }


def build_dimension_mean_table(strategy_results: dict[str, dict[str, pd.DataFrame | float]]) -> pd.DataFrame:
    rows = []
    for strategy, result in strategy_results.items():
        event = result["event_loss"]
        monthly = result["monthly_loss"]
        specs = [
            ("消费者福利", "LC", event["LC"]),
            ("企业与财政压力", "LF", event["LF"]),
            ("价格稳定性", "LV", event["LV"]),
            ("宏观稳定性", "Lpi", monthly["Lpi"]),
            ("能源安全与市场传导", "LE + LT", event["LE"] + event["LT"]),
        ]
        for dimension, loss_component, values in specs:
            rows.append(
                {
                    "strategy": strategy,
                    "dimension": dimension,
                    "loss_component": loss_component,
                    "mean_loss": float(values.mean()),
                    "sum_loss": float(values.sum()),
                    "n": int(values.shape[0]),
                }
            )
    return pd.DataFrame(rows)


def make_scenario_events(events: pd.DataFrame, positive_scale: float, negative_scale: float) -> pd.DataFrame:
    scenario = events.copy()
    scenario["f_gasoline"] = np.where(
        scenario["f_gasoline"] >= 0,
        scenario["f_gasoline"] * positive_scale,
        scenario["f_gasoline"] * negative_scale,
    )
    scenario["f_diesel"] = np.where(
        scenario["f_diesel"] >= 0,
        scenario["f_diesel"] * positive_scale,
        scenario["f_diesel"] * negative_scale,
    )
    return scenario


def run_robustness(
    events: pd.DataFrame,
    params: dict[str, float],
    weights: dict[str, float],
    gasoline_tree: DecisionTreeRegressor,
    diesel_tree: DecisionTreeRegressor,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    summary_rows = []
    dimension_frames = []
    for scenario in SCENARIOS:
        scenario_events = make_scenario_events(
            events,
            positive_scale=float(scenario["positive_scale"]),
            negative_scale=float(scenario["negative_scale"]),
        )
        rule_path = predict_rule_path(scenario_events, params, gasoline_tree, diesel_tree)
        full_eval = evaluate_adjustment_path(
            scenario_events,
            params,
            weights,
            scenario_events["f_gasoline"].to_numpy(),
            scenario_events["f_diesel"].to_numpy(),
            f"{scenario['scenario']}_full_transmission",
        )
        rule_eval = evaluate_adjustment_path(
            scenario_events,
            params,
            weights,
            rule_path["rule_u_gasoline"].to_numpy(),
            rule_path["rule_u_diesel"].to_numpy(),
            f"{scenario['scenario']}_simple_rule",
        )
        full_summary = summarize_strategy("full_transmission", full_eval)
        rule_summary = summarize_strategy("simple_rule", rule_eval)
        improvement = (
            full_summary["total_loss"] - rule_summary["total_loss"]
        ) / abs(full_summary["total_loss"])
        summary_rows.append(
            {
                **scenario,
                "full_transmission_total_loss": full_summary["total_loss"],
                "simple_rule_total_loss": rule_summary["total_loss"],
                "rule_improvement_vs_full_pct": improvement,
                "simple_rule_mean_alpha_gasoline": rule_path["alpha_rule_gasoline"].mean(),
                "simple_rule_mean_alpha_diesel": rule_path["alpha_rule_diesel"].mean(),
            }
        )
        dims = build_dimension_mean_table(
            {
                "full_transmission": full_eval,
                "simple_rule": rule_eval,
            }
        )
        dims.insert(0, "scenario", scenario["scenario"])
        dims.insert(1, "scenario_cn", scenario["scenario_cn"])
        dimension_frames.append(dims)
    return pd.DataFrame(summary_rows), pd.concat(dimension_frames, ignore_index=True)


def make_plots(
    dimension_summary: pd.DataFrame,
    robustness_summary: pd.DataFrame,
) -> None:
    dimension_en = {
        "消费者福利": "Consumer",
        "企业与财政压力": "Firm/fiscal",
        "价格稳定性": "Volatility",
        "宏观稳定性": "CPI",
        "能源安全与市场传导": "Energy/transmission",
    }
    plot_dims = dimension_summary.copy()
    plot_dims["dimension_en"] = plot_dims["dimension"].map(dimension_en)
    pivot = plot_dims.pivot(index="dimension_en", columns="strategy", values="mean_loss")
    order = ["Consumer", "Firm/fiscal", "Volatility", "CPI", "Energy/transmission"]
    pivot = pivot.loc[order]

    fig, ax = plt.subplots(figsize=(10, 5.5))
    x = np.arange(len(pivot))
    strategies = list(pivot.columns)
    width = 0.8 / len(strategies)
    for i, strategy in enumerate(strategies):
        ax.bar(x - 0.4 + width / 2 + i * width, pivot[strategy], width, label=strategy)
    ax.axhline(0, color="#333333", linewidth=0.8)
    ax.set_xticks(x, pivot.index, rotation=16, ha="right")
    ax.set_ylabel("Average loss")
    ax.set_title("Task 3 simplified-rule comparison")
    ax.grid(axis="y", alpha=0.25)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(RESULT_DIR / "task3_simple_rule_dimension_means.png", dpi=180)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(10, 5.5))
    scenario_labels = robustness_summary["scenario_en"]
    x = np.arange(len(robustness_summary))
    ax.plot(x, robustness_summary["full_transmission_total_loss"], marker="o", label="Full transmission")
    ax.plot(x, robustness_summary["simple_rule_total_loss"], marker="o", label="Simplified rule")
    ax.set_xticks(x, scenario_labels, rotation=20, ha="right")
    ax.set_ylabel("Total weighted loss")
    ax.set_title("Robustness under oil-price volatility uncertainty")
    ax.grid(alpha=0.25)
    ax.legend()
    fig.tight_layout()
    fig.savefig(RESULT_DIR / "task3_robustness_total_loss.png", dpi=180)
    plt.close(fig)


def main() -> None:
    events = pd.read_csv(RESULT_DIR / "task2_event_model_input_clean.csv", encoding="utf-8-sig")
    optimal = pd.read_csv(RESULT_DIR / "task2_optimization_equal_weight_final_step001_updated.csv", encoding="utf-8-sig")
    params = load_parameters()
    weights = get_weight_scenario("equal_weight")

    training = add_state_features(
        events,
        optimal["optimal_u_gasoline"].to_numpy(),
        optimal["optimal_u_diesel"].to_numpy(),
        params,
    )
    training["alpha_gasoline"] = optimal["alpha_gasoline"].to_numpy()
    training["alpha_diesel"] = optimal["alpha_diesel"].to_numpy()

    gasoline_tree, gasoline_metrics, gasoline_rules = fit_rule_tree(training, "gasoline")
    diesel_tree, diesel_metrics, diesel_rules = fit_rule_tree(training, "diesel")
    (RESULT_DIR / "task3_rule_tree_gasoline.txt").write_text(gasoline_rules, encoding="utf-8")
    (RESULT_DIR / "task3_rule_tree_diesel.txt").write_text(diesel_rules, encoding="utf-8")
    pd.DataFrame([gasoline_metrics, diesel_metrics]).to_csv(
        RESULT_DIR / "task3_rule_fit_metrics.csv",
        index=False,
        encoding="utf-8-sig",
    )

    rule_path = predict_rule_path(events, params, gasoline_tree, diesel_tree)
    rule_path.to_csv(
        RESULT_DIR / "task3_simple_rule_alpha_path.csv",
        index=False,
        encoding="utf-8-sig",
    )

    full_eval = evaluate_adjustment_path(
        events,
        params,
        weights,
        events["f_gasoline"].to_numpy(),
        events["f_diesel"].to_numpy(),
        "full_transmission",
    )
    current_eval = evaluate_adjustment_path(
        events,
        params,
        weights,
        events["u_hist_gasoline"].to_numpy(),
        events["u_hist_diesel"].to_numpy(),
        "current_mechanism",
    )
    optimal_eval = evaluate_adjustment_path(
        events,
        params,
        weights,
        optimal["optimal_u_gasoline"].to_numpy(),
        optimal["optimal_u_diesel"].to_numpy(),
        "optimal_alpha_star",
    )
    rule_eval = evaluate_adjustment_path(
        events,
        params,
        weights,
        rule_path["rule_u_gasoline"].to_numpy(),
        rule_path["rule_u_diesel"].to_numpy(),
        "simple_rule",
    )

    strategy_results = {
        "full_transmission": full_eval,
        "current_mechanism": current_eval,
        "optimal_alpha_star": optimal_eval,
        "simple_rule": rule_eval,
    }
    strategy_summary = pd.DataFrame(
        [summarize_strategy(strategy, result) for strategy, result in strategy_results.items()]
    )
    strategy_summary.to_csv(
        RESULT_DIR / "task3_simple_rule_strategy_comparison.csv",
        index=False,
        encoding="utf-8-sig",
    )
    dimension_summary = build_dimension_mean_table(strategy_results)
    dimension_summary.to_csv(
        RESULT_DIR / "task3_simple_rule_dimension_mean_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    robustness_summary, robustness_dims = run_robustness(
        events,
        params,
        weights,
        gasoline_tree,
        diesel_tree,
    )
    robustness_summary.to_csv(
        RESULT_DIR / "task3_robustness_scenario_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )
    robustness_dims.to_csv(
        RESULT_DIR / "task3_robustness_dimension_means.csv",
        index=False,
        encoding="utf-8-sig",
    )
    make_plots(dimension_summary, robustness_summary)

    print("Generated task-3 simple-rule and robustness outputs:")
    for name in [
        "task3_rule_tree_gasoline.txt",
        "task3_rule_tree_diesel.txt",
        "task3_rule_fit_metrics.csv",
        "task3_simple_rule_alpha_path.csv",
        "task3_simple_rule_strategy_comparison.csv",
        "task3_simple_rule_dimension_mean_summary.csv",
        "task3_robustness_scenario_summary.csv",
        "task3_robustness_dimension_means.csv",
        "task3_simple_rule_dimension_means.png",
        "task3_robustness_total_loss.png",
    ]:
        print(f"- {name}")
    print()
    print("Gasoline rule:")
    print(gasoline_rules)
    print("Diesel rule:")
    print(diesel_rules)
    print("Fit metrics:")
    print(pd.DataFrame([gasoline_metrics, diesel_metrics]).to_string(index=False))
    print("Baseline strategy comparison:")
    print(strategy_summary.to_string(index=False))
    print("Robustness summary:")
    print(robustness_summary.to_string(index=False))


if __name__ == "__main__":
    main()
